#!/bin/bash
# the virtual environment ${STOMPEST_DEV_VIRTUALENV} should contain the following
# packages and their dependencies (to be installed via pip install or easy-install):
# - stompest
# - stompest.async
# - sphinx
source ${STOMPEST_DEV_VIRTUALENV}/bin/activate
make html
